# Generated by Django 4.0 on 2022-03-12 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_userprofile_email_remove_userprofile_username'),
        ('blurts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlurtLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blurt_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blurts.blurt')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.userprofile')),
            ],
        ),
    ]
