# Generated by Django 4.0 on 2022-03-12 17:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blurts', '0002_blurtlikes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blurtlikes',
            old_name='user',
            new_name='user_profile',
        ),
        migrations.AddField(
            model_name='blurtlikes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
