# Generated by Django 4.0 on 2022-03-12 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_userprofile_email_remove_userprofile_username'),
        ('blurts', '0003_rename_user_blurtlikes_user_profile_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlurtLikes',
            new_name='BlurtLike',
        ),
    ]
