# Generated by Django 4.0 on 2022-03-12 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_userprofile_email_remove_userprofile_username'),
        ('blurts', '0004_rename_blurtlikes_blurtlike'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blurtlike',
            unique_together={('blurt_id', 'user_profile')},
        ),
    ]
