# Generated by Django 4.0 on 2022-03-12 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blurts', '0005_alter_blurtlike_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blurtlike',
            old_name='blurt_id',
            new_name='blurt',
        ),
    ]
