# Generated by Django 4.0 on 2022-03-17 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_userprofile_email_remove_userprofile_username'),
        ('blurts', '0006_rename_blurt_id_blurtlike_blurt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blurtlike',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
        migrations.CreateModel(
            name='BlurtComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
                ('blurt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blurts.blurt')),
            ],
        ),
    ]
