# Generated by Django 4.0 on 2022-03-21 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_userprofile_email_remove_userprofile_username'),
        ('blurts', '0008_alter_blurtcomment_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlurtCommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blurt_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blurts.blurtcomment')),
                ('user_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
            options={
                'unique_together': {('blurt_comment', 'user_profile')},
            },
        ),
    ]
